# Generated by Django 4.2.7 on 2023-12-08 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
           
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Evento sin nombre', max_length=100)),
                ('descripcion', models.TextField(default='Descripción del evento')),
                ('fecha', models.DateField(auto_now=True)),
            ],
        
             options={
                "db_table": "salon",
            },
        ),
    ]
